name: Create release package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: build extension
      run: make
    - name: create zip package
      run: make package
    - name: store zip package artifact
      uses: actions/upload-artifact@v1
      with:
        name: extension package
        path: _build/taskwhisperer.zip
